[
  {
    "state": "Alabama",
    "publicInfo": "33 (40.6)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "42 (41.5)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "27 (66)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "2 (81.9)",
    "executiveAccountabilityGrade": "grade-b",
    "legislativeAccountability": "4 (75.2)",
    "legislativeAccountabilityGrade": "grade-c",
    "judicialAccountability": "12 (61.8)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "33 (71.2)",
    "budgetProcessGrade": "grade-c",
    "civilService": "11 (66)",
    "civilServiceGrade": "grade-d",
    "procurement": "35 (65.4)",
    "procurementGrade": "grade-d",
    "internalAuditing": "4 (86.8)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "20 (66.3)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "5 (74.3)",
    "ethicsEnforcementGrade": "grade-c",
    "pensionFund": "7 (78.8)",
    "pensionFundGrade": "grade-c",
    "overall": "7 (67.4)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Alaska",
    "publicInfo": "34 (37.5)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "2 (88.2)",
    "politicalFinancingGrade": "grade-b",
    "electoralOversight": "25 (69.4)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "1 (88.5)",
    "executiveAccountabilityGrade": "grade-b",
    "legislativeAccountability": "1 (82.7)",
    "legislativeAccountabilityGrade": "grade-b",
    "judicialAccountability": "1 (81.7)",
    "judicialAccountabilityGrade": "grade-b",
    "budgetProcess": "18 (78.6)",
    "budgetProcessGrade": "grade-c",
    "civilService": "9 (67.5)",
    "civilServiceGrade": "grade-d",
    "procurement": "19 (73.8)",
    "procurementGrade": "grade-c",
    "internalAuditing": "17 (82.6)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "1 (97.5)",
    "lobbyingDisclosureScore": "grade-a",
    "ethicsEnforcement": "2 (79.6)",
    "ethicsEnforcementGrade": "grade-c",
    "pensionFund": "27 (62.5)",
    "pensionFundGrade": "grade-d",
    "overall": "1 (76.2)",
    "overallGrade": "grade-c"
  },
  {
    "state": "Arizona",
    "publicInfo": "20 (48.8)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "26 (61)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "13 (73.6)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "31 (57.8)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "14 (67.3)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "2 (76.8)",
    "judicialAccountabilityGrade": "grade-c",
    "budgetProcess": "44 (64.8)",
    "budgetProcessGrade": "grade-d",
    "civilService": "39 (55.2)",
    "civilServiceGrade": "grade-f",
    "procurement": "12 (76.7)",
    "procurementGrade": "grade-c",
    "internalAuditing": "4 (86.8)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "40 (53.8)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "27 (56.7)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "45 (47.9)",
    "pensionFundGrade": "grade-f",
    "overall": "22 (63.6)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Arkansas",
    "publicInfo": "16 (52.2)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "30 (55.3)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "29 (62.5)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "26 (60.3)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "46 (50.1)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "9 (62.5)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "14 (83.4)",
    "budgetProcessGrade": "grade-b",
    "civilService": "28 (59.4)",
    "civilServiceGrade": "grade-f",
    "procurement": "22 (70)",
    "procurementGrade": "grade-c",
    "internalAuditing": "47 (63.2)",
    "internalAuditingScore": "grade-d",
    "lobbyingDisclosure": "35 (55.8)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "11 (65.3)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "37 (55)",
    "pensionFundGrade": "grade-f",
    "overall": "32 (61.2)",
    "overallGrade": "grade-d"
  },
  {
    "state": "California",
    "publicInfo": "28 (43.8)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "10 (71)",
    "politicalFinancingGrade": "grade-c",
    "electoralOversight": "17 (71.5)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "5 (73)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "11 (70.3)",
    "legislativeAccountabilityGrade": "grade-c",
    "judicialAccountability": "20 (57.8)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "6 (90.6)",
    "budgetProcessGrade": "grade-a",
    "civilService": "10 (67.4)",
    "civilServiceGrade": "grade-d",
    "procurement": "21 (71.7)",
    "procurementGrade": "grade-c",
    "internalAuditing": "25 (81.3)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "2 (87.9)",
    "lobbyingDisclosureScore": "grade-b",
    "ethicsEnforcement": "4 (75.2)",
    "ethicsEnforcementGrade": "grade-c",
    "pensionFund": "2 (93.8)",
    "pensionFundGrade": "grade-a",
    "overall": "2 (73.5)",
    "overallGrade": "grade-c"
  },
  {
    "state": "Colorado",
    "publicInfo": "34 (37.5)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "19 (66)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "8 (76.4)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "14 (68.6)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "3 (75.8)",
    "legislativeAccountabilityGrade": "grade-c",
    "judicialAccountability": "6 (66.2)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "9 (88.8)",
    "budgetProcessGrade": "grade-b",
    "civilService": "22 (61.9)",
    "civilServiceGrade": "grade-d",
    "procurement": "10 (77.1)",
    "procurementGrade": "grade-c",
    "internalAuditing": "17 (82.6)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "22 (64.2)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "44 (42.3)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "32 (60.4)",
    "pensionFundGrade": "grade-d",
    "overall": "13 (66.8)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Connecticut",
    "publicInfo": "7 (58.8)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "8 (72.4)",
    "politicalFinancingGrade": "grade-c",
    "electoralOversight": "16 (72.2)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "18 (64.3)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "7 (72.2)",
    "legislativeAccountabilityGrade": "grade-c",
    "judicialAccountability": "41 (49.2)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "10 (88)",
    "budgetProcessGrade": "grade-b",
    "civilService": "23 (60.8)",
    "civilServiceGrade": "grade-d",
    "procurement": "27 (68.3)",
    "procurementGrade": "grade-d",
    "internalAuditing": "41 (74.3)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "3 (78.3)",
    "lobbyingDisclosureScore": "grade-c",
    "ethicsEnforcement": "10 (66.5)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "1 (95)",
    "pensionFundGrade": "grade-a",
    "overall": "3 (70.8)",
    "overallGrade": "grade-c"
  },
  {
    "state": "Delaware",
    "publicInfo": "24 (45.6)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "27 (59)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "23 (69.4)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "36 (56)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "48 (48.7)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "46 (46.2)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "42 (65.1)",
    "budgetProcessGrade": "grade-d",
    "civilService": "43 (54.3)",
    "civilServiceGrade": "grade-f",
    "procurement": "31 (66.3)",
    "procurementGrade": "grade-d",
    "internalAuditing": "43 (72.9)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "34 (56.3)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "43 (45.5)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "48 (36.7)",
    "pensionFundGrade": "grade-f",
    "overall": "48 (55.5)",
    "overallGrade": "grade-f"
  },
  {
    "state": "Florida",
    "publicInfo": "17 (50.6)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "28 (58.7)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "46 (50)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "16 (67.4)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "2 (76.9)",
    "legislativeAccountabilityGrade": "grade-c",
    "judicialAccountability": "38 (51.2)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "49 (55.6)",
    "budgetProcessGrade": "grade-f",
    "civilService": "50 (50.1)",
    "civilServiceGrade": "grade-f",
    "procurement": "25 (68.8)",
    "procurementGrade": "grade-d",
    "internalAuditing": "10 (85.4)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "38 (54.6)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "18 (62.9)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "22 (65)",
    "pensionFundGrade": "grade-d",
    "overall": "30 (61.3)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Georgia",
    "publicInfo": "28 (43.8)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "38 (45.3)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "14 (72.9)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "29 (58.8)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "6 (73)",
    "legislativeAccountabilityGrade": "grade-c",
    "judicialAccountability": "15 (60.5)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "39 (66.6)",
    "budgetProcessGrade": "grade-d",
    "civilService": "14 (64.8)",
    "civilServiceGrade": "grade-d",
    "procurement": "38 (63.8)",
    "procurementGrade": "grade-d",
    "internalAuditing": "2 (88.2)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "46 (49.6)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "21 (60.2)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "18 (69.6)",
    "pensionFundGrade": "grade-d",
    "overall": "24 (62.8)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Hawaii",
    "publicInfo": "2 (70)",
    "publicInfoGrade": "grade-c",
    "politicalFinancing": "11 (70.6)",
    "politicalFinancingGrade": "grade-c",
    "electoralOversight": "34 (59.7)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "11 (70.9)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "24 (62.8)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "26 (56.3)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "33 (71.2)",
    "budgetProcessGrade": "grade-c",
    "civilService": "13 (65.1)",
    "civilServiceGrade": "grade-d",
    "procurement": "13 (76.3)",
    "procurementGrade": "grade-c",
    "internalAuditing": "15 (84)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "37 (55)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "3 (79.1)",
    "ethicsEnforcementGrade": "grade-c",
    "pensionFund": "13 (73.8)",
    "pensionFundGrade": "grade-c",
    "overall": "4 (68.8)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Idaho",
    "publicInfo": "6 (61.3)",
    "publicInfoGrade": "grade-d",
    "politicalFinancing": "15 (67.4)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "3 (84.7)",
    "electoralOversightGrade": "grade-b",
    "executiveAccountability": "49 (37.6)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "47 (49.9)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "39 (51)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "2 (95.9)",
    "budgetProcessGrade": "grade-a",
    "civilService": "36 (55.7)",
    "civilServiceGrade": "grade-f",
    "procurement": "29 (67.5)",
    "procurementGrade": "grade-d",
    "internalAuditing": "10 (85.4)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "17 (67.5)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "47 (39.3)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "46 (44.6)",
    "pensionFundGrade": "grade-f",
    "overall": "26 (62.1)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Illinois",
    "publicInfo": "15 (52.5)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "7 (74.1)",
    "politicalFinancingGrade": "grade-c",
    "electoralOversight": "15 (72.2)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "33 (57.2)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "31 (60.5)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "43 (48.7)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "47 (57.8)",
    "budgetProcessGrade": "grade-f",
    "civilService": "31 (59)",
    "civilServiceGrade": "grade-f",
    "procurement": "1 (86.3)",
    "procurementGrade": "grade-b",
    "internalAuditing": "10 (85.4)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "19 (66.7)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "23 (58.8)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "4 (89.2)",
    "pensionFundGrade": "grade-b",
    "overall": "13 (66.8)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Indiana",
    "publicInfo": "23 (46.9)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "47 (37.7)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "25 (69.4)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "25 (60.5)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "34 (59.9)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "31 (54.7)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "48 (56.2)",
    "budgetProcessGrade": "grade-f",
    "civilService": "35 (56.3)",
    "civilServiceGrade": "grade-f",
    "procurement": "29 (67.5)",
    "procurementGrade": "grade-d",
    "internalAuditing": "27 (79.9)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "15 (68.3)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "31 (54.4)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "5 (87.9)",
    "pensionFundGrade": "grade-b",
    "overall": "29 (61.5)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Iowa",
    "publicInfo": "1 (72.8)",
    "publicInfoGrade": "grade-c",
    "politicalFinancing": "25 (61.6)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "31 (61.1)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "17 (65.1)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "15 (66.1)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "21 (57.7)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "13 (83.6)",
    "budgetProcessGrade": "grade-b",
    "civilService": "19 (62.6)",
    "civilServiceGrade": "grade-d",
    "procurement": "42 (60.4)",
    "procurementGrade": "grade-d",
    "internalAuditing": "17 (82.6)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "41 (53.3)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "6 (71.5)",
    "ethicsEnforcementGrade": "grade-c",
    "pensionFund": "13 (73.8)",
    "pensionFundGrade": "grade-c",
    "overall": "9 (67.1)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Kansas",
    "publicInfo": "13 (53.8)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "6 (74.9)",
    "politicalFinancingGrade": "grade-c",
    "electoralOversight": "37 (57.6)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "32 (57.2)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "28 (61.8)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "43 (48.7)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "46 (58.6)",
    "budgetProcessGrade": "grade-f",
    "civilService": "25 (60.4)",
    "civilServiceGrade": "grade-d",
    "procurement": "49 (48.8)",
    "procurementGrade": "grade-f",
    "internalAuditing": "50 (53.5)",
    "internalAuditingScore": "grade-f",
    "lobbyingDisclosure": "29 (59.2)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "28 (56)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "16 (72.9)",
    "pensionFundGrade": "grade-c",
    "overall": "42 (58.7)",
    "overallGrade": "grade-f"
  },
  {
    "state": "Kentucky",
    "publicInfo": "8 (58.1)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "4 (81.5)",
    "politicalFinancingGrade": "grade-b",
    "electoralOversight": "28 (64.6)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "13 (69.7)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "5 (73.5)",
    "legislativeAccountabilityGrade": "grade-c",
    "judicialAccountability": "28 (55.7)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "28 (73.8)",
    "budgetProcessGrade": "grade-c",
    "civilService": "8 (68)",
    "civilServiceGrade": "grade-d",
    "procurement": "5 (80.4)",
    "procurementGrade": "grade-b",
    "internalAuditing": "45 (64.6)",
    "internalAuditingScore": "grade-d",
    "lobbyingDisclosure": "20 (66.3)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "40 (51.2)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "22 (65)",
    "pensionFundGrade": "grade-d",
    "overall": "9 (67.1)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Louisiana",
    "publicInfo": "46 (29.7)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "22 (64)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "23 (69.4)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "40 (52.8)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "38 (58.3)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "49 (40)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "38 (67)",
    "budgetProcessGrade": "grade-d",
    "civilService": "38 (55.5)",
    "civilServiceGrade": "grade-f",
    "procurement": "25 (68.8)",
    "procurementGrade": "grade-d",
    "internalAuditing": "32 (78.5)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "24 (63.8)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "22 (59.8)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "34 (56.7)",
    "pensionFundGrade": "grade-f",
    "overall": "41 (58.8)",
    "overallGrade": "grade-f"
  },
  {
    "state": "Maine",
    "publicInfo": "26 (45.3)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "20 (65.5)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "47 (45.1)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "28 (58.9)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "16 (65.6)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "34 (53.2)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "29 (73.4)",
    "budgetProcessGrade": "grade-c",
    "civilService": "32 (57.7)",
    "civilServiceGrade": "grade-f",
    "procurement": "44 (56.7)",
    "procurementGrade": "grade-f",
    "internalAuditing": "35 (77.8)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "8 (72.5)",
    "lobbyingDisclosureScore": "grade-c",
    "ethicsEnforcement": "46 (40.3)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "41 (50.4)",
    "pensionFundGrade": "grade-f",
    "overall": "43 (58.6)",
    "overallGrade": "grade-f"
  },
  {
    "state": "Maryland",
    "publicInfo": "41 (34.1)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "23 (62.7)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "9 (75)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "24 (62.8)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "22 (63.2)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "7 (63.7)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "21 (76.6)",
    "budgetProcessGrade": "grade-c",
    "civilService": "5 (69.5)",
    "civilServiceGrade": "grade-c",
    "procurement": "16 (74.6)",
    "procurementGrade": "grade-c",
    "internalAuditing": "49 (54.9)",
    "internalAuditingScore": "grade-f",
    "lobbyingDisclosure": "7 (74.2)",
    "lobbyingDisclosureScore": "grade-c",
    "ethicsEnforcement": "29 (55.9)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "33 (58.8)",
    "pensionFundGrade": "grade-f",
    "overall": "23 (63.5)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Massachusetts",
    "publicInfo": "40 (34.4)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "1 (92)",
    "politicalFinancingGrade": "grade-a",
    "electoralOversight": "6 (80.6)",
    "electoralOversightGrade": "grade-b",
    "executiveAccountability": "23 (62.9)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "17 (65.3)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "27 (56)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "41 (65.5)",
    "budgetProcessGrade": "grade-d",
    "civilService": "17 (63.2)",
    "civilServiceGrade": "grade-d",
    "procurement": "4 (81.3)",
    "procurementGrade": "grade-b",
    "internalAuditing": "17 (82.6)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "30 (58.3)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "15 (64.5)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "21 (65.4)",
    "pensionFundGrade": "grade-d",
    "overall": "9 (67.1)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Michigan",
    "publicInfo": "42 (33.8)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "32 (51.6)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "5 (81.3)",
    "electoralOversightGrade": "grade-b",
    "executiveAccountability": "50 (26.8)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "50 (36.3)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "50 (29.5)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "8 (88.9)",
    "budgetProcessGrade": "grade-b",
    "civilService": "37 (55.6)",
    "civilServiceGrade": "grade-f",
    "procurement": "46 (53.8)",
    "procurementGrade": "grade-f",
    "internalAuditing": "32 (78.5)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "43 (50.8)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "48 (37.9)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "50 (30.4)",
    "pensionFundGrade": "grade-f",
    "overall": "50 (50.4)",
    "overallGrade": "grade-f"
  },
  {
    "state": "Minnesota",
    "publicInfo": "24 (45.6)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "17 (66.8)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "6 (80.6)",
    "electoralOversightGrade": "grade-b",
    "executiveAccountability": "37 (55.6)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "44 (53)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "30 (55)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "24 (74.4)",
    "budgetProcessGrade": "grade-c",
    "civilService": "16 (63.2)",
    "civilServiceGrade": "grade-d",
    "procurement": "31 (66.3)",
    "procurementGrade": "grade-d",
    "internalAuditing": "10 (85.4)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "25 (62.5)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "37 (51.9)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "47 (43.3)",
    "pensionFundGrade": "grade-f",
    "overall": "28 (61.8)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Mississippi",
    "publicInfo": "21 (47.2)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "50 (33.8)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "42 (56.3)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "39 (53.9)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "19 (64.1)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "24 (56.8)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "31 (72.5)",
    "budgetProcessGrade": "grade-c",
    "civilService": "21 (62)",
    "civilServiceGrade": "grade-d",
    "procurement": "31 (66.3)",
    "procurementGrade": "grade-d",
    "internalAuditing": "30 (79.2)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "12 (69.6)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "9 (66.9)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "29 (61.3)",
    "pensionFundGrade": "grade-d",
    "overall": "33 (60.8)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Missouri",
    "publicInfo": "18 (50.3)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "44 (40.6)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "42 (56.3)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "3 (75.4)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "37 (58.8)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "5 (67.2)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "43 (65)",
    "budgetProcessGrade": "grade-d",
    "civilService": "29 (59.3)",
    "civilServiceGrade": "grade-f",
    "procurement": "41 (63.3)",
    "procurementGrade": "grade-d",
    "internalAuditing": "17 (82.6)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "10 (70.8)",
    "lobbyingDisclosureScore": "grade-c",
    "ethicsEnforcement": "14 (64.7)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "38 (52.5)",
    "pensionFundGrade": "grade-f",
    "overall": "26 (62.1)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Montana",
    "publicInfo": "42 (33.8)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "15 (67.4)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "17 (71.5)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "10 (71)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "8 (71.3)",
    "legislativeAccountabilityGrade": "grade-c",
    "judicialAccountability": "16 (60.3)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "37 (69.3)",
    "budgetProcessGrade": "grade-d",
    "civilService": "34 (57.7)",
    "civilServiceGrade": "grade-f",
    "procurement": "16 (74.6)",
    "procurementGrade": "grade-c",
    "internalAuditing": "30 (79.2)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "42 (52.5)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "24 (58.3)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "24 (63.8)",
    "pensionFundGrade": "grade-d",
    "overall": "21 (63.9)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Nebraska",
    "publicInfo": "8 (58.1)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "39 (44.5)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "2 (85.4)",
    "electoralOversightGrade": "grade-b",
    "executiveAccountability": "34 (57)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "27 (61.9)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "13 (61.2)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "1 (96.9)",
    "budgetProcessGrade": "grade-a",
    "civilService": "29 (59.3)",
    "civilServiceGrade": "grade-f",
    "procurement": "6 (79.6)",
    "procurementGrade": "grade-b",
    "internalAuditing": "36 (77.1)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "11 (70.8)",
    "lobbyingDisclosureScore": "grade-c",
    "ethicsEnforcement": "34 (53.8)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "20 (68.3)",
    "pensionFundGrade": "grade-d",
    "overall": "8 (67.2)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Nevada",
    "publicInfo": "28 (43.8)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "34 (49.9)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "35 (58.3)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "8 (71.2)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "25 (62.3)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "35 (52.8)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "22 (76.2)",
    "budgetProcessGrade": "grade-c",
    "civilService": "7 (68.1)",
    "civilServiceGrade": "grade-d",
    "procurement": "47 (49.6)",
    "procurementGrade": "grade-f",
    "internalAuditing": "48 (55.6)",
    "internalAuditingScore": "grade-f",
    "lobbyingDisclosure": "50 (38.8)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "35 (53.5)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "29 (61.3)",
    "pensionFundGrade": "grade-d",
    "overall": "46 (57)",
    "overallGrade": "grade-f"
  },
  {
    "state": "New Hampshire",
    "publicInfo": "49 (24.4)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "33 (51.3)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "36 (58.3)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "4 (74.3)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "29 (61.6)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "36 (52.2)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "20 (76.6)",
    "budgetProcessGrade": "grade-c",
    "civilService": "18 (62.6)",
    "civilServiceGrade": "grade-d",
    "procurement": "35 (65.4)",
    "procurementGrade": "grade-d",
    "internalAuditing": "39 (75.7)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "25 (62.5)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "39 (51.3)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "15 (72.9)",
    "pensionFundGrade": "grade-c",
    "overall": "34 (60.7)",
    "overallGrade": "grade-d"
  },
  {
    "state": "New Jersey",
    "publicInfo": "27 (44.1)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "14 (67.7)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "50 (22.2)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "42 (51.7)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "12 (67.8)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "18 (58.5)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "15 (83)",
    "budgetProcessGrade": "grade-b",
    "civilService": "2 (71.5)",
    "civilServiceGrade": "grade-c",
    "procurement": "15 (75.8)",
    "procurementGrade": "grade-c",
    "internalAuditing": "26 (80.6)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "6 (74.6)",
    "lobbyingDisclosureScore": "grade-c",
    "ethicsEnforcement": "19 (62.9)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "7 (78.8)",
    "pensionFundGrade": "grade-c",
    "overall": "19 (64.6)",
    "overallGrade": "grade-d"
  },
  {
    "state": "New Mexico",
    "publicInfo": "19 (49.1)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "36 (47.9)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "33 (60.4)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "41 (52.5)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "39 (57.1)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "3 (72.7)",
    "judicialAccountabilityGrade": "grade-c",
    "budgetProcess": "26 (74.1)",
    "budgetProcessGrade": "grade-c",
    "civilService": "14 (64.8)",
    "civilServiceGrade": "grade-d",
    "procurement": "38 (63.8)",
    "procurementGrade": "grade-d",
    "internalAuditing": "17 (82.6)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "43 (50.8)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "45 (41.3)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "17 (71.3)",
    "pensionFundGrade": "grade-c",
    "overall": "35 (60.6)",
    "overallGrade": "grade-d"
  },
  {
    "state": "New York",
    "publicInfo": "11 (55.3)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "24 (62.4)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "49 (38.9)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "15 (68.4)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "26 (62.3)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "48 (42.5)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "50 (52.2)",
    "budgetProcessGrade": "grade-f",
    "civilService": "1 (72)",
    "civilServiceGrade": "grade-c",
    "procurement": "48 (49.2)",
    "procurementGrade": "grade-f",
    "internalAuditing": "1 (88.9)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "5 (76.7)",
    "lobbyingDisclosureScore": "grade-c",
    "ethicsEnforcement": "36 (52)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "10 (76.7)",
    "pensionFundGrade": "grade-c",
    "overall": "30 (61.3)",
    "overallGrade": "grade-d"
  },
  {
    "state": "North Carolina",
    "publicInfo": "39 (35.6)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "5 (75.3)",
    "politicalFinancingGrade": "grade-c",
    "electoralOversight": "20 (70.8)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "12 (70.7)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "10 (70.8)",
    "legislativeAccountabilityGrade": "grade-c",
    "judicialAccountability": "29 (55.2)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "19 (78)",
    "budgetProcessGrade": "grade-c",
    "civilService": "45 (53.9)",
    "civilServiceGrade": "grade-f",
    "procurement": "10 (77.1)",
    "procurementGrade": "grade-c",
    "internalAuditing": "36 (77.1)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "22 (64.2)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "20 (62.8)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "39 (51.7)",
    "pensionFundGrade": "grade-f",
    "overall": "18 (64.8)",
    "overallGrade": "grade-d"
  },
  {
    "state": "North Dakota",
    "publicInfo": "10 (56.6)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "45 (39.5)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "1 (86.8)",
    "electoralOversightGrade": "grade-b",
    "executiveAccountability": "43 (50.7)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "43 (56.2)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "9 (62.5)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "16 (79.6)",
    "budgetProcessGrade": "grade-c",
    "civilService": "49 (50.2)",
    "civilServiceGrade": "grade-f",
    "procurement": "19 (73.8)",
    "procurementGrade": "grade-c",
    "internalAuditing": "27 (79.9)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "47 (40.8)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "33 (54.2)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "42 (50)",
    "pensionFundGrade": "grade-f",
    "overall": "37 (60.1)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Ohio",
    "publicInfo": "47 (29.1)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "18 (66.6)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "9 (75)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "22 (63.1)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "23 (62.9)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "17 (60)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "35 (70.3)",
    "budgetProcessGrade": "grade-c",
    "civilService": "20 (62.4)",
    "civilServiceGrade": "grade-d",
    "procurement": "7 (78.3)",
    "procurementGrade": "grade-c",
    "internalAuditing": "17 (82.6)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "4 (77.5)",
    "lobbyingDisclosureScore": "grade-c",
    "ethicsEnforcement": "16 (63.6)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "3 (90)",
    "pensionFundGrade": "grade-a",
    "overall": "6 (67.8)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Oklahoma",
    "publicInfo": "44 (32.5)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "13 (68.6)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "37 (57.6)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "35 (56.4)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "35 (59.9)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "45 (47.7)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "45 (61.8)",
    "budgetProcessGrade": "grade-d",
    "civilService": "32 (57.7)",
    "civilServiceGrade": "grade-f",
    "procurement": "7 (78.3)",
    "procurementGrade": "grade-c",
    "internalAuditing": "10 (85.4)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "38 (54.6)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "37 (51.9)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "34 (56.7)",
    "pensionFundGrade": "grade-f",
    "overall": "40 (59.2)",
    "overallGrade": "grade-f"
  },
  {
    "state": "Oregon",
    "publicInfo": "34 (37.5)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "49 (36.5)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "11 (74.3)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "38 (54.5)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "30 (61)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "32 (54.5)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "27 (73.8)",
    "budgetProcessGrade": "grade-c",
    "civilService": "12 (65.7)",
    "civilServiceGrade": "grade-d",
    "procurement": "45 (55)",
    "procurementGrade": "grade-f",
    "internalAuditing": "36 (77.1)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "30 (58.3)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "25 (58)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "43 (48.8)",
    "pensionFundGrade": "grade-f",
    "overall": "44 (58.1)",
    "overallGrade": "grade-f"
  },
  {
    "state": "Pennsylvania",
    "publicInfo": "4 (67.8)",
    "publicInfoGrade": "grade-d",
    "politicalFinancing": "43 (41.1)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "48 (41)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "20 (63.7)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "42 (56.5)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "47 (43)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "30 (72.6)",
    "budgetProcessGrade": "grade-c",
    "civilService": "44 (54)",
    "civilServiceGrade": "grade-f",
    "procurement": "38 (63.8)",
    "procurementGrade": "grade-d",
    "internalAuditing": "27 (79.9)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "25 (62.5)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "30 (55.8)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "40 (50.8)",
    "pensionFundGrade": "grade-f",
    "overall": "45 (57.9)",
    "overallGrade": "grade-f"
  },
  {
    "state": "Rhode Island",
    "publicInfo": "5 (64.7)",
    "publicInfoGrade": "grade-d",
    "politicalFinancing": "9 (71.6)",
    "politicalFinancingGrade": "grade-c",
    "electoralOversight": "37 (57.6)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "7 (71.7)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "20 (63.8)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "7 (63.7)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "40 (66)",
    "budgetProcessGrade": "grade-d",
    "civilService": "6 (69)",
    "civilServiceGrade": "grade-d",
    "procurement": "23 (69.6)",
    "procurementGrade": "grade-d",
    "internalAuditing": "45 (64.6)",
    "internalAuditingScore": "grade-d",
    "lobbyingDisclosure": "12 (69.6)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "1 (80.7)",
    "ethicsEnforcementGrade": "grade-b",
    "pensionFund": "11 (76.3)",
    "pensionFundGrade": "grade-c",
    "overall": "5 (68.4)",
    "overallGrade": "grade-d"
  },
  {
    "state": "South Carolina",
    "publicInfo": "44 (32.5)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "37 (47.5)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "30 (61.8)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "27 (59.6)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "41 (56.8)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "25 (56.7)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "36 (70)",
    "budgetProcessGrade": "grade-c",
    "civilService": "26 (59.9)",
    "civilServiceGrade": "grade-d",
    "procurement": "31 (66.3)",
    "procurementGrade": "grade-d",
    "internalAuditing": "8 (86.1)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "18 (67.1)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "26 (57.9)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "24 (63.8)",
    "pensionFundGrade": "grade-d",
    "overall": "36 (60.5)",
    "overallGrade": "grade-d"
  },
  {
    "state": "South Dakota",
    "publicInfo": "21 (47.2)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "35 (48.8)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "42 (56.3)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "46 (46.9)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "45 (52.9)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "14 (60.7)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "17 (79.2)",
    "budgetProcessGrade": "grade-c",
    "civilService": "47 (50.7)",
    "civilServiceGrade": "grade-f",
    "procurement": "43 (60)",
    "procurementGrade": "grade-d",
    "internalAuditing": "17 (82.6)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "49 (39.6)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "42 (47.7)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "36 (56.3)",
    "pensionFundGrade": "grade-f",
    "overall": "47 (56.1)",
    "overallGrade": "grade-f"
  },
  {
    "state": "Tennessee",
    "publicInfo": "37 (37.2)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "21 (65.1)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "12 (73.6)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "9 (71.1)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "21 (63.3)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "37 (51.3)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "12 (86.3)",
    "budgetProcessGrade": "grade-b",
    "civilService": "4 (69.9)",
    "civilServiceGrade": "grade-c",
    "procurement": "27 (68.3)",
    "procurementGrade": "grade-d",
    "internalAuditing": "2 (88.2)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "14 (68.8)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "32 (54.3)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "26 (62.9)",
    "pensionFundGrade": "grade-d",
    "overall": "15 (66.2)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Texas",
    "publicInfo": "48 (25.9)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "41 (43)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "45 (52.1)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "44 (49.7)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "36 (58.9)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "41 (49.2)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "4 (91)",
    "budgetProcessGrade": "grade-a",
    "civilService": "41 (54.7)",
    "civilServiceGrade": "grade-f",
    "procurement": "9 (77.9)",
    "procurementGrade": "grade-c",
    "internalAuditing": "4 (86.8)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "45 (50)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "17 (63.1)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "9 (77.5)",
    "pensionFundGrade": "grade-c",
    "overall": "38 (60)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Utah",
    "publicInfo": "2 (70)",
    "publicInfoGrade": "grade-c",
    "politicalFinancing": "40 (43.7)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "17 (71.5)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "45 (48.5)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "13 (67.7)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "23 (57.5)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "7 (90.1)",
    "budgetProcessGrade": "grade-a",
    "civilService": "42 (54.5)",
    "civilServiceGrade": "grade-f",
    "procurement": "3 (83.3)",
    "procurementGrade": "grade-b",
    "internalAuditing": "15 (84)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "35 (55.8)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "41 (48.3)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "49 (34.2)",
    "pensionFundGrade": "grade-f",
    "overall": "25 (62.2)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Vermont",
    "publicInfo": "12 (55)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "3 (84.3)",
    "politicalFinancingGrade": "grade-b",
    "electoralOversight": "31 (61.1)",
    "electoralOversightGrade": "grade-d",
    "executiveAccountability": "48 (38.7)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "49 (38.8)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "21 (57.7)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "5 (90.8)",
    "budgetProcessGrade": "grade-a",
    "civilService": "40 (54.8)",
    "civilServiceGrade": "grade-f",
    "procurement": "23 (69.6)",
    "procurementGrade": "grade-d",
    "internalAuditing": "44 (70.1)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "9 (71.3)",
    "lobbyingDisclosureScore": "grade-c",
    "ethicsEnforcement": "50 (23)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "29 (61.3)",
    "pensionFundGrade": "grade-d",
    "overall": "39 (59.7)",
    "overallGrade": "grade-f"
  },
  {
    "state": "Virginia",
    "publicInfo": "38 (35.9)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "46 (39.3)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "4 (81.9)",
    "electoralOversightGrade": "grade-b",
    "executiveAccountability": "19 (63.7)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "18 (64.3)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "4 (72)",
    "judicialAccountabilityGrade": "grade-c",
    "budgetProcess": "32 (71.6)",
    "budgetProcessGrade": "grade-c",
    "civilService": "3 (70.4)",
    "civilServiceGrade": "grade-c",
    "procurement": "2 (85.8)",
    "procurementGrade": "grade-b",
    "internalAuditing": "8 (86.1)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "30 (58.3)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "13 (64.8)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "27 (62.5)",
    "pensionFundGrade": "grade-d",
    "overall": "16 (65.9)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Washington",
    "publicInfo": "32 (42.2)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "12 (69.9)",
    "politicalFinancingGrade": "grade-d",
    "electoralOversight": "20 (70.8)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "30 (58.5)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "32 (60.3)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "11 (62)",
    "judicialAccountabilityGrade": "grade-d",
    "budgetProcess": "23 (75.6)",
    "budgetProcessGrade": "grade-c",
    "civilService": "27 (59.9)",
    "civilServiceGrade": "grade-d",
    "procurement": "13 (76.3)",
    "procurementGrade": "grade-c",
    "internalAuditing": "4 (86.8)",
    "internalAuditingScore": "grade-b",
    "lobbyingDisclosure": "28 (61.7)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "7 (71.1)",
    "ethicsEnforcementGrade": "grade-c",
    "pensionFund": "12 (75.8)",
    "pensionFundGrade": "grade-c",
    "overall": "12 (67)",
    "overallGrade": "grade-d"
  },
  {
    "state": "West Virginia",
    "publicInfo": "28 (43.8)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "31 (55.2)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "40 (56.9)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "6 (72.7)",
    "executiveAccountabilityGrade": "grade-c",
    "legislativeAccountability": "8 (71.3)",
    "legislativeAccountabilityGrade": "grade-c",
    "judicialAccountability": "18 (58.5)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "25 (74.2)",
    "budgetProcessGrade": "grade-c",
    "civilService": "24 (60.7)",
    "civilServiceGrade": "grade-d",
    "procurement": "35 (65.4)",
    "procurementGrade": "grade-d",
    "internalAuditing": "32 (78.5)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "16 (67.9)",
    "lobbyingDisclosureScore": "grade-d",
    "ethicsEnforcement": "8 (69.8)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "6 (80)",
    "pensionFundGrade": "grade-b",
    "overall": "17 (65.8)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Wisconsin",
    "publicInfo": "13 (53.8)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "29 (57.5)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "20 (70.8)",
    "electoralOversightGrade": "grade-c",
    "executiveAccountability": "21 (63.6)",
    "executiveAccountabilityGrade": "grade-d",
    "legislativeAccountability": "40 (56.8)",
    "legislativeAccountabilityGrade": "grade-f",
    "judicialAccountability": "33 (53.3)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "11 (86.5)",
    "budgetProcessGrade": "grade-b",
    "civilService": "48 (50.5)",
    "civilServiceGrade": "grade-f",
    "procurement": "16 (74.6)",
    "procurementGrade": "grade-c",
    "internalAuditing": "41 (74.3)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "33 (56.7)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "12 (64.9)",
    "ethicsEnforcementGrade": "grade-d",
    "pensionFund": "18 (69.6)",
    "pensionFundGrade": "grade-d",
    "overall": "20 (64.1)",
    "overallGrade": "grade-d"
  },
  {
    "state": "Wyoming",
    "publicInfo": "50 (22.5)",
    "publicInfoGrade": "grade-f",
    "politicalFinancing": "48 (36.9)",
    "politicalFinancingGrade": "grade-f",
    "electoralOversight": "40 (56.9)",
    "electoralOversightGrade": "grade-f",
    "executiveAccountability": "47 (46.7)",
    "executiveAccountabilityGrade": "grade-f",
    "legislativeAccountability": "33 (60.1)",
    "legislativeAccountabilityGrade": "grade-d",
    "judicialAccountability": "40 (49.3)",
    "judicialAccountabilityGrade": "grade-f",
    "budgetProcess": "3 (93.4)",
    "budgetProcessGrade": "grade-a",
    "civilService": "46 (51.2)",
    "civilServiceGrade": "grade-f",
    "procurement": "50 (44.2)",
    "procurementGrade": "grade-f",
    "internalAuditing": "40 (75)",
    "internalAuditingScore": "grade-c",
    "lobbyingDisclosure": "48 (40)",
    "lobbyingDisclosureScore": "grade-f",
    "ethicsEnforcement": "48 (37.9)",
    "ethicsEnforcementGrade": "grade-f",
    "pensionFund": "44 (47.9)",
    "pensionFundGrade": "grade-f",
    "overall": "49 (50.9)",
    "overallGrade": "grade-f"
  }
]